biocore/microsetta-interface

- microsetta_interface/templates/sample_results.jinja2
> Missing parens after migrating document.ready callback

- microsetta_interface/static/vendor/emperor/emperor_loader.js
> Sets scale for 'self' points in pcoa to 2.5 rather than 1.5

- microsetta_interface/templates/create_nonhuman_source.jinja2
> Name input required for new environmental sources

- microsetta_interface/implementation.py
- microsetta_interface/routes.yaml
- microsetta_interface/templates/post_sample_questionnaire.jinja2
- microsetta_interface/templates/source.jinja2
Fix #51 
New page after editing sample info asks user if they want to take ffq (unless they already took it)
Based on issue info, may need to merge in some tooltip functionality once tooltip goes in.
> After Sample Edit, Ask For FFQ

- microsetta_interface/templates/source.jinja2
Fix #56 
Wrapped header columns in a container div so they'd be offset the same as the list group items
> Missing container div

- microsetta_interface/templates/account_details.jinja2
Account details page now shows the selected state rather than defaulting to first state in list
> Fix Details Show Alabama

- microsetta_interface/templates/account_details.jinja2
UK is reserved but wrong - UK is not the official country code
Should fix UK (GB, hah.) legacy users checking their profile and seeing US, Alabama
> Use country code GB instead of country code UK 

- microsetta_interface/templates/new_results_page.jinja2
Fills in the How You Compare tab.  
updateCompare now fills in available text fields.  Still waiting on more URLs for bacterial and archaeal counts, so it's a work in progress.
> WIP: How you compare tab of cool results

- microsetta_interface/templates/new_results_page.jinja2
Uses alpha group diversity to make faith pd plot in Plotly rather than vega
> Plotly Percentile Plot

- microsetta_interface/templates/new_results_page.jinja2
* Can treat both dataset and data type as a single variable in the UI.  
* All values depend on Dataset (Data Type is merging with dataset)
Collapsed Dataset and Data Type into just Dataset.  Some hacky workarounds for jquery event handling while Emperor is loading in.  Ajax is used to fill dataset.
> Merge dataset and data type select boxes, use ajax

- microsetta_interface/templates/new_results_page.jinja2
Adds the ajax requests and transformations to build the taxonomy violin plot from the mockups.
> Cool Results Page: Plotly Taxa Violin Plot

- microsetta_interface/implementation.py
We no longer ask user to fill in vioscreen survey immediately after entering sample info for environmental or animal samples
> Fix - Stop asking for vioscreen surveys for non human samples

- microsetta_interface/templates/new_results_page.jinja2
@dhakim87 or @gwarmstrong, this is a very small PR to close out two milestone issues
> Results page tweaks

- microsetta_interface/templates/source.jinja2
For disabled buttons, it's necessary to add "pointer-events: none"
> Fix tooltip for source removal

- microsetta_interface/templates/new_results_page.jinja2
> Bolded and localized bacteria and archaea counts

- microsetta_interface/static/vendor/DataTables/PercentageBars-1.10.21/js/percentageBars.js
- microsetta_interface/templates/new_results_page.jinja2
> What is in your sample revisions

- microsetta_interface/templates/new_results_page.jinja2
Adds a new tab with info about the dataset
> New dataset info tab (How can you learn more?)

- microsetta_interface/templates/sample_results.jinja2
...this hot fix restores the temporary results, tested on oral/skin/fecal samples. Am merging directly, and pushing to production
> We broke the temporary results on the last deploy

- microsetta_interface/templates/new_results_page.jinja2
> minor typo

- microsetta_interface/templates/new_results_page.jinja2
Daniel - please check the change I made to " Your microbiome is a rainforest of diverse microbes dominated by microbes". I am not sure what you mean by this. All other changes should be straightforward.
> made a few grammar edits

- microsetta_interface/implementation.py
If we have a fecal sample, let's use the new results page
> Use the new results page if fecal

- microsetta_interface/implementation.py
- microsetta_interface/server.py
en-US to en_US everywhere.  Hooked browser settings and account language settings to ApiRequests so that we query surveys in the right language.
This is blocked by the account language preferences changes.
> en-US to en_US and using flask session

- microsetta_interface/implementation.py
- microsetta_interface/redis_cache.py
- microsetta_interface/server.py
- microsetta_interface/templates/admin_system_panel.jinja2
- microsetta_interface/templates/sitebase.jinja2
Created a dictionary for possible system messages, which only contains one entry at the moment.
Adjusted jinja2 template to add fields for shutdown hours/minutes and revamped the JavaScript to show the preview of the message.
> System Message i18n

- microsetta_interface/implementation.py
- microsetta_interface/model_i18n.py
Adds translations for sample.sample_site, source.source_type and survey_template.survey_template_title
> Translate Enums in Private API Model Objects

- microsetta_interface/implementation.py
- microsetta_interface/model_i18n.py
- microsetta_interface/templates/account_details.jinja2
- microsetta_interface/templates/admin_system_panel.jinja2
- microsetta_interface/templates/home.jinja2
- microsetta_interface/templates/new_results_page.jinja2
- microsetta_interface/templates/sample.jinja2
- microsetta_interface/templates/sitebase.jinja2
And build a LANGUAGES data structure for iterating over
Fix #173
> Centralize en_us en_US es_mx es_MX strings

- microsetta_interface/implementation.py
- microsetta_interface/routes.yaml
- microsetta_interface/templates/admin_address_verification.jinja2
- microsetta_interface/templates/sitebase.jinja2
- microsetta_interface/util.py
Added a new page to the admin side of the interface with the ability to either manually verify one address or upload a CSV of addresses. Created functions to pass information back and forth to Private API to perform the actual address verification with Melissa.
> Interface Changes for Address Verification

- microsetta_interface/implementation.py
- microsetta_interface/routes.yaml
- microsetta_interface/templates/admin_barcode_search.jinja2
> Interface side for querying qiita for barcode information

- microsetta_interface/templates/account_overview.jinja2
- microsetta_interface/templates/embedded_pdf.jinja2
- microsetta_interface/translations/en_US/LC_MESSAGES/messages.po
- microsetta_interface/translations/es_MX/LC_MESSAGES/messages.po
Just some minor items spotted during deploy testing
> A few missed items

- microsetta_interface/implementation.py
- microsetta_interface/model_i18n.py
- microsetta_interface/routes.yaml
- microsetta_interface/templates/myfoodrepo_no_slots.jinja2
- microsetta_interface/templates/secondary_surveys.jinja2
- microsetta_interface/templates/source.jinja2
- microsetta_interface/tests/test_integration.py
> Secondary survey support including and myfoodrepo hand off

- microsetta_interface/implementation.py
Address feedback from @sejsong
> Open "learn more" in a new tab"

- microsetta_interface/translations/es_MX/LC_MESSAGES/messages.po
Babel did a bit of reorg on the file
> Translations we missed on recent updates

- microsetta_interface/implementation.py
- microsetta_interface/tests/test_integration.py
Interface portion of oils & oxalates survey
> Cooking Oils & Oxalate-rich Foods Survey

- microsetta_interface/templates/survey.jinja2
resized and verified page display with Cassidy
tested responsiveness
> bristol stool chart image resizing to fit page better

- microsetta_interface/templates/new_results_page.jinja2
This PR removes unused code, adds a prioritized detection the data types associated with a sample, abstracts out data type specific elements, and allows data from wgs endpoints to be displayed. This PR also adds the disclaimer "No evidence presented here indicates what we’ve observed is clinically dangerous" to the taxonomy summary. 
cc @sejsong @cassidysymons
> Display support for wgs samples

- microsetta_interface/translations/ja_JP/LC_MESSAGES/messages.po
Minor text changes requested by Japanese collaborators. Per Se Jin, I have permission to merge these without peer review due to urgency.
> Changes requested by Japanese collaborators

- microsetta_interface/templates/kits.jinja2
- microsetta_interface/templates/new_results_page.jinja2
- microsetta_interface/templates/reports.jinja2
> Change "Results" to "Report"

- microsetta_interface/templates/update_address.jinja2
Change phone from optional to required on /update_address
> Require Phone on Address Update

- microsetta_interface/implementation.py
- microsetta_interface/templates/admin_home.jinja2
Only this repo needs to be updated because all account-related information is already outputted by the private API.
> Add AuthRocket Status to account search

- microsetta_interface/templates/new_results_page.jinja2
Adjusted CSS for containers on the Diversity tab to display at a more appropriate size on mobile devices.
> Improvements to Report Template for Mobile

- microsetta_interface/templates/sitebase.jinja2
- Placed all buttons except email and logout under dropdown menu
- Added margins to left and right ends
> Restructure Admin Menu

- microsetta_interface/model_i18n.py
Removed Japanese as an option for preferred language for those that select Japan as their country.
> Japanese locale

- .github/workflows/main.yml
Changing from "ubuntu-latest" to "ubuntu-22.04" to resolve workflow issue
> Fix Workflow

- .github/workflows/main.yml
> Merge master into csymons_skin_surveys

- microsetta_interface/static/css/minimal_interface.css
- microsetta_interface/templates/kits.jinja2
Make the div surrounding all the barcode buttons on the "My Kits" web page a flex grid. Now all the buttons wrap and are responsive.
Fixes Issue #323
> style: add flex grid CSS to outer div of barcode buttons to enable wrap
