biocore/microsetta-interface

microsetta_interface/templates/sample.jinja2

Fixes sample_notes to not display None to the user when no notes are set.  Instead we show a placeholder asking for any additional information they wish to provide
Fix #8

Sample Notes Don't Say None

---

microsetta_interface/templates/survey.jinja2

Fix #13 
Moved code out of surrounding if statement - this prevented question triggers from being linked up when a survey had no top level questions, only questions that were inside of grouped categories.

Question Triggers Weren't Hooked Up

---

microsetta_interface/templates/account_details.jinja2

New PR that targets only the account_details page.
* Changed name of page to "profile" to reflect purpose of page
* Added asterisks to clarify that each input field is required
* Changed button text to reflect its action
* Moved note about non-U.S. participants to be higher
* Moved CA option to be in alphabetical order (although if possible--could the default option be set to blank, as I believe now the default option would be Alabama?)

Update account_details.jinja2 (only)

---

microsetta_interface/templates/account_overview.jinja2

Turns out the issue is a result of taking zeplin at its word, css-wise.  Unfortunately, its auto-generated, overly-specified boilerplate css doesn't include backup fonts, thus defaulting to Times New Roman if one doesn't have Muli ... it also references css variables that we don't have defined :(. I've tried to excise the bits that are either breaking things or unused in the page.  Now looks like this:

fixes #39 (inconsistent fonts on page)

---

microsetta_interface/templates/sample.jinja2

Fix #2 
Used jquery validate to validate date on the sample page.  Required a custom validator function which was cobbled together from the jquery-validate additional-methods plugins/examples file

Enforce MM/DD/YYYY for Sample Date

---

microsetta_interface/templates/new_results_page.jinja2

Hacky fix for emperor not understanding how to set width when it is embedded inside bootstrap tabs.  This workaround triggers a window resize event when the tab containing the emperor control is selected.

Emperor width workaround

---

microsetta_interface/implementation.py

Interface side of vioscreen hotfix.  This should give us enough information to rebuild which user has which vioscreen survey if they never get redirected back to us.

Pass sample_id to vioscreen url generation

---

microsetta_interface/implementation.py
microsetta_interface/templates/source.jinja2

One case where we had users getting broken pdf links was from them having a status of 0, 1, or 2 in the database and having a -DISTINCT- vioscreen survey ID from their primary ID (matching these two still forces them to take a new survey as of now)
Uses vioscreen status to decide whether to show report pdf or questionnaire
Relies on matching PR in microsetta-private-api.

Fix broken vioscreen pdf links

---

microsetta_interface/static/input_util.js
microsetta_interface/templates/create_nonhuman_source.jinja2

Added utility method to disable form inputs and change their text on form submit, used in create_nonhuman_source
We'll have to do something like this on all the forms we don't want users button mashing on.  Also, firefox prevents form submit button mashing by default, so rather difficult to reproduce on there.  
Fix #103

Template for fixing button mashing

---

microsetta_interface/templates/source.jinja2

Adds a tool tip for removal of a sample when the removal is not possible. I cannot get the positioning perfect, it looks like it is aligning to the middle of the div rather than the button. Attempting to place it directly on the button did not immediately work. I think we should defer this for a future review of the tooltip aesthetics, and focus right now on tool tip content.

Tool tip on remove sample

---

microsetta_interface/templates/new_participant.jinja2
microsetta_interface/templates/survey.jinja2

1) On new_participant.jinja2, there are two groups of changes:
1a) Not all fields that are required were actually shown as required to the user - I standardized that
1b) The asterisk for required fields was breaking onto a new line - I formatted it to be red and show up on the same line with cleaned-up visuals
2) On survey.jinja2:
2a) I paginated the form by field group
2b) Added buttons for Previous & Next Section
2c) Added a progress bar to the top of the screen
2d) Add a one-time confirm on submit since responses can't be edited
2e) Made some font weight and size changes to decrease the wall-of-text effect
(note, depends on biocore/microsetta-private-api#315)

Survey Aesthetics

---

microsetta_interface/implementation.py
microsetta_interface/routes.yaml
microsetta_interface/templates/account_details.jinja2
microsetta_interface/templates/admin_activation_codes.jinja2
microsetta_interface/templates/sitebase.jinja2

Lets user enter an Activation Code instead of a Kit ID to login.  
Probably shouldn't merge this until there is actually a way to distribute activation codes to users??

Account Creation by Activation Code

---

babel.cfg
messages.pot
microsetta_interface/implementation.py
microsetta_interface/server.py
microsetta_interface/templates/sample.jinja2

First pass over implementation.py to add support for gettext and properly format dates.  
Added a super basic babel config, will need to add to it to support javascript, but should work for python and jinja2.  
To regenerate messages.pot (after you add gettext calls to python or jinja2 templates):
cd to root directory of checkout
pybabel extract -F babel.cfg -o messages.pot .
To check if your new strings made it past the extract call, 
cat messages.pot and look for your strings.

Adds messages.pot and first usages of gettext

---

microsetta_interface/implementation.py
microsetta_interface/static/vendor/jquery-ui-i18n/README.txt
microsetta_interface/static/vendor/jquery-ui-i18n/datepicker-es.js
microsetta_interface/templates/sample.jinja2

Fixes the date portion of #139   
Localization of sample date field.  Introduces a hidden normalized field that is always mm/dd/yyyy.  Replaces validation to localize the normalized field on init, and normalize the localized field on validation.  Uses the jquery datepicker's i18n extensions for configuring the datepicker.
Far as I can tell, Spanish should be on a 24 hour clock, 8:00 AM -> 8:00, 8:00 PM -> 20:00.  Can add this in this branch as well.

i18n datepicker

---

microsetta_interface/implementation.py

...without it, `None` is returned violating OpenAPI3 validation

BUG: fallback to default on best_match

---

microsetta_interface/implementation.py
microsetta_interface/templates/account_details.jinja2

Lets user update email through LoginRocket by redirecting from Account Details page.  Fixes crash on missing language when user wants to update their email.

Users can update email address

---

.github/workflows/main.yml
README.md
keys_for_testing.sh
microsetta_interface/implementation.py
microsetta_interface/tests/test_integration.py

This PR couples with biocore/microsetta-private-api#412 to provide a means for running integration tests within Github Actions (and locally as well).
There are a few pieces included here:
- a modified github actions script which includes a job to pull microsetta-private-api, install it, and execute the integration tests
- generation of JWT public/private keys
- a means to use new public/private keys at server start
- examples of fake users interacting with the system including login
The test suite provides ways to construct new users which are completely valid from the perspective of authentication, and includes the use of a de-identified user that exists in the test database to assert routing in the state machine.

Setup an integration test harness

---

microsetta_interface/templates/sample.jinja2
microsetta_interface/templates/survey.jinja2
microsetta_interface/translations/en_US/LC_MESSAGES/messages.po

limit the collection date that can be selected for a sample.

Limit Sample Collection Date

---

.github/workflows/main.yml

Adding an environment variable to the job that installs Microsetta Private API. If the pull request or push here on Microsetta Interface is being issued against master-overhaul, the job will clone the master-overhaul branch of Private API. Otherwise, it will clone the master branch of Private API.
This allows all work on the overhaul branch of Interface to successfully run integration tests against the overhaul branch of Private API, while all other branches will continue to run against master.

Adjust workflow for overhaul

---

.github/workflows/main.yml

github.ref wasn't returning the desired information, tested using github.base_ref and it works as intended for pull requests

Workflow fix for overhaul

---

microsetta_interface/implementation.py
microsetta_interface/templates/account_details.jinja2
microsetta_interface/tests/test_integration.py

This pull contains the changes pertinent to the kit id and activation code removal from signup form. This is from master-overhaul branch of my new fork to biocore/master-overhaul removal

Kit_id and activation code removal change from a fresh fork

---

microsetta_interface/implementation.py

For THDMI Spain, we made the decision to hide the Vioscreen option to minimize confusion, as it won't work in Spain. This behavior is working correctly on the Source page, as the Vioscreen FFQ button is not displayed for Spanish users. However, during testing, we missed the post-sample page that encourages the user to take the Vioscreen FFQ.
This change mirrors the logic of determining a Spanish user (either their account country or locale matching Spain) and, if it does, bypasses the redirect to the page suggesting they take the Vioscreen FFQ.

Spain Vioscreen Bypass

---

microsetta_interface/templates/sample.jinja2

Date validation on sample details was not using the hidden normalized date field, so ambiguous dates such as October 12 (10/12 vs. 12/10 depending on locale) were running afoul of the rule about being more than 30 days in the future. Moved the validation further down the chain so it can use the normalized value and function correctly.

Adjust date validation for i18n issues

---

microsetta_interface/implementation.py
microsetta_interface/model_i18n.py
microsetta_interface/static/vendor/jquery-validation/messages_ja_jp.js
microsetta_interface/templates/account_details.jinja2
microsetta_interface/templates/admin_campaign_edit.jinja2
microsetta_interface/templates/submit_interest.jinja2
microsetta_interface/translations/ja_JP/LC_MESSAGES/messages.po

The scope of this PR is to support THDMI Japan signups using the Interested Users form on the existing platform. The actual THDMI Japan campaign will be launched on the new version of the TMI platform, so these PRs explicitly exclude Japanese translations for the consent documents and surveys.
To prevent the edge case of an existing account changing their account to Japanese and/or someone with an existing Kit ID/Activation Code from creating an account and selecting Japanese, I've prevented it from displaying as a language option in the Account Details screen.
Added:
- ja_JP locale
- workaound to prevent a user from selecting Japanese as their account language since localized consents/surveys are not available
- Japan-specific address entry panel to submit_interest.jinja2, including …

Changes for THDMI Japan signups

---

microsetta_interface/implementation.py
microsetta_interface/templates/admin_campaign_edit.jinja2
microsetta_interface/templates/submit_interest.jinja2
microsetta_interface/translations/ja_JP/LC_MESSAGES/messages.po

This PR corresponds to https://github.com/biocore/microsetta-private-api/pull/482 and includes the interface changes necessary to support that.
In addition:
1) Removes US phone validation as a default rule on submit_interest.jinja2. Now, phone is required, but it will only validate format when a user selects United States as the country. In the future, per-country phone validation would be ideal, but since it's the tertiary mode of contact in this context, it's unimportant.
2) Updates a few strings in messages.po for ja_JP

Changed requested by Japanese collaborators

---

ci/conda_requirements.txt

@wasade And this one as well, please.

Pin flask-babel

---

microsetta_interface/implementation.py
microsetta_interface/model_i18n.py

For the initial relaunch period, we're disabling Japanese as timing prevented us from completing a full review with the Tokyo Tech team.

Disable Japanese Locale

---

microsetta_interface/templates/new_participant.jinja2
microsetta_interface/templates/new_results_page.jinja2
microsetta_interface/translations/es_ES/LC_MESSAGES/messages.po
microsetta_interface/translations/es_MX/LC_MESSAGES/messages.po

This update forces profiles/sources with an `age_range` of `legacy` to select an age group before re-consenting.
In addition, the breadcrumbs on the report page have been updated to fit the convention introduced with the UI overhaul.

Handle Re-consent for Legacy Sources

---

microsetta_interface/implementation.py
microsetta_interface/routes.yaml
microsetta_interface/static/css/minimal_interface.css
microsetta_interface/templates/account_overview.jinja2
microsetta_interface/templates/consents.jinja2
microsetta_interface/templates/kits.jinja2
microsetta_interface/templates/new_participant.jinja2
microsetta_interface/templates/nutrition.jinja2
microsetta_interface/templates/reports.jinja2
microsetta_interface/templates/sample.jinja2
microsetta_interface/templates/signed_consent.jinja2
microsetta_interface/templates/sitebase.jinja2
microsetta_interface/templates/source.jinja2
microsetta_interface/templates/survey.jinja2
microsetta_interface/translations/es_ES/LC_MESSAGES/messages.po
microsetta_interface/translations/es_MX/LC_MESSAGES/messages.po

- Add consent decline warning to default Profile page
- Add ability for legacy sources to cancel re-consent without selecting an age range
- Add message to Consent Documents page for users who don't reconsent
- Hide next/previous survey info for users who didn't reconsent
- Disable Skip/Display functionality for users who haven't reconsented
- Disallow participants who did not reconsent from continuing an existing FFQ
- Fix View Results button alignment on My Kits tab
- Fix disable_link() on Reports tab
- Change top-left logo to go to /home rather than https://microsetta.ucsd.edu/
- Change "Not Completed" to "Needs Review" on survey cards for existing users who have answered at least one question in a newly reorganized survey template
- Add last taken/time estimates to mobile survey cards …

Addressing Feedback from Production Testing

---

microsetta_interface/implementation.py
microsetta_interface/templates/update_address.jinja2

In concert with https://github.com/biocore/microsetta-private-api/pull/538, this adjustment gracefully handles null/None values for address_2

Address Adjustment Improvement

---

ci/pip_requirements.txt

Connexion 3.0 was released earlier this month and is breaking workflow. Pinning it to < 3.0.0.

Pin connexion[swagger-ui]

---

microsetta_interface/templates/sample.jinja2

Two adjustments:
* Change the back-dating limit from 10 years to 1 year
* Allow admin accounts to bypass the limits

Adjust Date Limits for Sample Collection Info

---

microsetta_interface/implementation.py
microsetta_interface/tests/test_integration.py

Add description of error code linked to https://github.com/biocore/microsetta-private-api/pull/549
Note: Spanish translations will not be available until Monday 2023-12-04. Do not merge until then.

Block PO Boxes

---

microsetta_interface/templates/reports.jinja2

Added last_update column to ag_kit_barcodes table to microsetta-private-api, [PR here](https://github.com/biocore/microsetta-private-api/pull/558). This will enable a more descriptive sample status on the 'My Reports' tab.
The new sample statuses are as followed.
- Not Yet Received (Sample has not be scanned yet)
- Sample Received - Report Pending (Sample has been scanned and has the necessary information, now just awaiting Report generation)
- Sample Received - Update Pending (Sample has been updated with new information but has not been scanned yet)
- Sample Received - Information Needed (Sample has been scanned but lacks necessary information)
- Sample Received - Information Still Needed (Sample has been updated with new information and has been scanned but it still lacks necessary …

added new sample statuses

---

microsetta_interface/implementation.py
microsetta_interface/routes.yaml
microsetta_interface/templates/account_details.jinja2
microsetta_interface/templates/admin_requests_account_removal_list.jinja2
microsetta_interface/templates/request_account_deletion_confirm.jinja2
microsetta_interface/templates/sitebase.jinja2
microsetta_interface/tests/test_integration.py

This pushes https://github.com/biocore/microsetta-interface/pull/267 over the finish line to allow an admin to delete an account (admin is prompted to supply a reason for account deletion)

Account deletion request final

---

microsetta_interface/templates/new_results_page.jinja2

This pull request changes the alpha diversity metric used in the stool report from observed_features to shannon and updates supporting text accordingly.

Change Alpha Diversity Metric

---

.github/workflows/main.yml

The change from "ubuntu-latest" to "ubuntu-22.04" was working two days ago but is now failing for the lint check. Looking at microsetta-private-api's workflow, it uses action/setup-python@v2 rather than @v1, switching to that.

Adjust Workflow

---

microsetta_interface/implementation.py
microsetta_interface/routes.yaml
microsetta_interface/static/css/minimal_interface.css
microsetta_interface/templates/kits.jinja2
microsetta_interface/templates/sample.jinja2
microsetta_interface/tests/test_integration.py

This pull request addresses two issues:
1) It better handles Null/None values being returned for cheek samples' barcode_meta fields.
2) It adds a prompt for users who have just edited a cheek sample to take the Skin Scoring App external survey. Given that we have no insight into whether a user has actually completed the app process (by submitting a selfie), we've opted to display this message whenever a cheek sample is edited and the skin scoring app survey is available to the user.

SBI Pre-launch Adjustments
